localization_node:
  ros__parameters:
    ekf_period_s: 0.01
    Qt_0: 100.0 #Measurement noise
    Qt_1: 100.0
    Mt_0: 1 #Process noise
    Mt_1: 1
    Mt_2: 1
    initial_pose: [-0.5, -0.5, 0.0]
    initial_covariance: [0.1, 0.1, 0.1]
    landmark1: [0,0]
    landmark2: [1,0]
    landmark3: [1,1]
    landmark4: [0,1]
    landmark5: [-1,1]
    landmark6: [-1,0]
    landmark7: [-1,-1]
    landmark8: [0,-1]
    landmark9: [1,-1]
    std_rot1: 0.017453292519943295 
    std_transl: 0.1
    std_rot2: 0.017453292519943295
    std_lin_vel: 0.0 #0.1 Not in use
    std_ang_vel: 0.0 #0.017453292519943295 Not in use
    std_rng: 0.0 #0.3
    std_brg: 0.0 #0.017453292519943295
    max_range: 8.0
    fov_deg: 180.0

